language: cpp
sudo: required
dist: trusty


matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"


before_install:
    - eval "${MATRIX_EVAL}"


script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make
    - ctest --verbose
    - gcov -n -o . src/gqf.cpp > /dev/null;
after_success:
    - bash <(curl -s https://codecov.io/bash)


branches:
  only:
  - mqfDevelopmenet
  - master

