language: cpp
sudo: required
dist: trusty
compiler:
- g++
os:
- linux


before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y make automake autotools-dev cmake
script:
  - mkdir -p build
  - cmake ..
  - ctest
  - gcov -n -o . src/gqf.cpp > /dev/null;
branches:
  only:
  - mqfDevelopmenet
  - master

after_success:
  - bash <(curl -s https://codecov.io/bash)
